name: agorachat
description: "Agora chat and voice call Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # API
  dio: ^5.7.0

  # Agora
  agora_chat_sdk: ^1.3.2
  agora_rtc_engine: ^6.3.2

  # Voice message recording and playing
  record: ^6.0.0
  just_audio: ^0.9.42

  # Permissions
  permission_handler: ^11.3.1

  # File/path handling
  path_provider: ^2.1.5

  # Localization/date formatting
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true