import 'package:agora_rtc_engine/agora_rtc_engine.dart';
import '../../../core/constants/agora_constants.dart';

/// Wraps Agora RTC Engine for one-to-one voice calls.
///
/// How it works:
/// 1. [init] creates the engine and sets up event callbacks.
/// 2. [join] requests the user to broadcast audio in [channelName] using [token].
///    The token is generated server-side and scoped to a specific channel + UID.
/// 3. [leave] exits the channel gracefully.
/// 4. [dispose] releases all native resources — must be called when done.
class VoiceCallRepository {
  late RtcEngine _engine;
  bool _isInitialised = false;

  // ─── Callbacks set by the screen ──────────────────────────────────────────

  void Function(int remoteUid)? onRemoteUserJoined;
  void Function(int remoteUid)? onRemoteUserLeft;
  void Function()? onJoinedChannel;
  void Function(String error)? onError;

  // ─── Lifecycle ─────────────────────────────────────────────────────────────

  Future<void> init() async {
    if (_isInitialised) return;

    _engine = createAgoraRtcEngine();

    await _engine.initialize(
      RtcEngineContext(
        appId: AgoraConstants.appId,
        channelProfile: ChannelProfileType.channelProfileCommunication,
      ),
    );

    _engine.registerEventHandler(
      RtcEngineEventHandler(
        onJoinChannelSuccess: (connection, elapsed) {
          onJoinedChannel?.call();
        },
        onUserJoined: (connection, remoteUid, elapsed) {
          onRemoteUserJoined?.call(remoteUid);
        },
        onUserOffline: (connection, remoteUid, reason) {
          onRemoteUserLeft?.call(remoteUid);
        },
        onError: (err, msg) {
          onError?.call('RTC error [$err]: $msg');
        },
      ),
    );

    await _engine.enableAudio();
    _isInitialised = true;
  }

  /// Joins an RTC channel.
  ///
  /// [token] — time-limited token generated by your server using the App Certificate.
  /// [channelName] — must match the channel used when generating the token.
  /// [uid] — 0 lets Agora assign one automatically.
  Future<void> join({
    required String token,
    required String channelName,
    int uid = 0,
  }) async {
    await _engine.joinChannel(
      token: token,
      channelId: channelName,
      uid: uid,
      options: const ChannelMediaOptions(
        autoSubscribeAudio: true,
        publishMicrophoneTrack: true,
        clientRoleType: ClientRoleType.clientRoleBroadcaster,
      ),
    );
  }

  Future<void> leave() async {
    if (!_isInitialised) return;
    await _engine.leaveChannel();
  }

  Future<void> dispose() async {
    if (!_isInitialised) return;
    await _engine.leaveChannel();
    await _engine.release();
    _isInitialised = false;
  }

  // ─── Controls ──────────────────────────────────────────────────────────────

  Future<void> muteLocalAudio({required bool mute}) async {
    await _engine.muteLocalAudioStream(mute);
  }

  Future<void> setSpeakerphone({required bool enabled}) async {
    await _engine.setEnableSpeakerphone(enabled);
  }
}
